server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LISEESEE/springcloud-config.git #GitHub上面的git仓库名字
          force-pull: true
          username: 641307158@qq.com
          password: lisensen952102

        ####搜索目录
          search-paths:
            - springcloud-config

      ####读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: 192.168.1.51
    port: 5672
    username: admin
    password: admin
    virtual-host: vhost_test
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

#群发
#curl -X POST "http://localhost:3344/actuator/bus-refresh"
#定点通知
#curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"